### ISSUE TITLE
docker-compose 版本 admin/123456 無法登入 UI

### ISSUE THREAD

**Issue by changchichung** [eryajf/go-ldap-admin#210]
#### 您使用的版本？ | Your usage version?
v0.5.10 2023-04-25

#### 您遇到了什么问题？ | What are your problems?

開啟 http://localhost:8090 用 admin / 123456 無法登入

出現 http error code 502
![](https://i.imgur.com/c0UhDnL.jpg)

容器的log 如下
```
[DEBUG wait] --------------------------------------------------------
[INFO  wait] Checking availability of host [mysql:3306]
[INFO  wait] Host [mysql:3306] is now available!
[INFO  wait] --------------------------------------------------------
[INFO  wait] Checking availability of host [ openldap:389]
[INFO  wait] Host [ openldap:389] is now available!
[INFO  wait] --------------------------------------------------------
[INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
[INFO  wait] --------------------------------------------------------
2023-05-10 14:35:07	INFO	common/logger.go:110	github.com/eryajf/go-ldap-admin/public/common.InitLogger	初始化zap日志完成!
2023-05-10 14:35:07	INFO	common/database.go:91	github.com/eryajf/go-ldap-admin/public/common.ConnMysql	初始化mysql数据库完成! dsn: root:******@tcp(mysql:3306)/go_ldap_admin?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms
2023-05-10 14:35:07	PANIC	common/ldap.go:38	github.com/eryajf/go-ldap-admin/public/common.InitLDAP	绑定admin账号异常: LDAP Result Code 49 "Invalid Credentials": 
panic: 绑定admin账号异常: LDAP Result Code 49 "Invalid Credentials": 

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00061a000, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*SugaredLogger).log(0xc000010638, 0x4, {0x12ab8b1?, 0xc000706000?}, {0xc000591d88?, 0x916b8a?, 0x0?}, {0x0, 0x0, 0x0})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/go/pkg/mod/go.uber.org/zap@v1.19.1/sugar.go:159
github.com/eryajf/go-ldap-admin/public/common.InitLDAP()
	/app/public/common/ldap.go:38 +0x425
main.main()
	/app/main.go:32 +0x54
```

**Comment by eryajf** [comment]
您好 @changchichung👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @changchichung. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
根本原因是server连接ldap失败，导致服务没有正常启动，从而无法使用后台管理功能。

你的server对接的ldap是一起部署的，还是对接的已有的ldap，需要你解决一下这块儿的连接问题。

**Comment by shiningstarts** [comment]
> 我的 docker-compose.yml
> 
> ```
> version: '3'
> 
> networks:
>   go-ldap-admin:
>     driver: bridge
> 
> services:
>   mysql:
>     image: dockerproxy.com/mysql/mysql-server:5.7
>     container_name: go-ldap-admin-mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
>     hostname: go-ldap-admin-mysql
>     restart: always # 设置容器自启模式
>     ports:
>       - '3307:3306'
>     environment:
>       TZ: Asia/Taipei # 设置容器时区与宿主机保持一致
>       MYSQL_ROOT_PASSWORD: 123456 # 设置root密码
>       MYSQL_ROOT_HOST: "%"
>       MYSQL_DATABASE: go_ldap_admin
>     volumes:
>       # 数据挂载目录自行修改哦！
>       - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
>       - ./data/mysql:/var/lib/mysql/data # 映射数据库保存目录到宿主机，防止数据丢失
>       - ./config/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件
>     command: --default-authentication-plugin=mysql_native_password #解决外部无法访问
>     networks:
>       - go-ldap-admin
> 
>   openldap:
>     image: dockerproxy.com/osixia/openldap:1.4.0
>     container_name: go-ldap-admin-openldap
>     hostname: go-ldap-admin-openldap
>     restart: always
>     environment:
>       TZ: Asia/Shanghai
>       LDAP_ORGANISATION: "abc.com"
>       LDAP_DOMAIN: "abc.com"
>       LDAP_ADMIN_PASSWORD: "123456"
>     command: [ '--copy-service' ]
>     volumes:
>       - ./data/openldap/database:/var/lib/ldap
>       - ./data/openldap/config:/etc/ldap/slapd.d
>       - ./config/init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/init.ldif
>     ports:
>       - 388:389
>     networks:
>       - go-ldap-admin
> 
>   phpldapadmin:
>     image: dockerproxy.com/osixia/phpldapadmin:0.9.0
>     container_name: go-ldap-admin-phpldapadmin
>     hostname: go-ldap-admin-phpldapadmin
>     restart: always
>     environment:
>       TZ: Asia/Taipei # 设置容器时区与宿主机保持一致
>       PHPLDAPADMIN_HTTPS: "false" # 是否使用https
>       PHPLDAPADMIN_LDAP_HOSTS: go-ldap-admin-openldap # 指定LDAP容器名称
>     ports:
>       - 8091:80
>     volumes:
>       - ./data/phpadmin:/var/www/phpldapadmin
>     depends_on:
>       - openldap
>     links:
>       - openldap:go-ldap-admin-openldap # ldap容器的 service_name:container_name
>     networks:
>       - go-ldap-admin
> 
>   go-ldap-admin-server:
>     image: dockerproxy.com/eryajf/go-ldap-admin-server
>     container_name: go-ldap-admin-server
>     hostname: go-ldap-admin-server
>     restart: always
>     environment:
>       TZ: Asia/Taipei
>       WAIT_HOSTS: mysql:3306, openldap:389
>     ports:
>       - 8888:8888
>     # volumes:  # 可按需打开此配置，将配置文件挂载到本地 可在服务运行之后，执行 docker cp go-ldap-admin-server:/app/config.yml ./config 然后再取消该行注释
>     #   - ./config/config.yml:/app/config.yml
>     depends_on:
>       - mysql
>       - openldap
>     links:
>       - mysql:go-ldap-admin-mysql # ldap容器的 service_name:container_name
>       - openldap:go-ldap-admin-openldap # ldap容器的 service_name:container_name
>     networks:
>       - go-ldap-admin
> 
>   go-ldap-admin-ui:
>     image: dockerproxy.com/eryajf/go-ldap-admin-ui
>     container_name: go-ldap-admin-ui
>     hostname: go-ldap-admin-ui
>     restart: always
>     environment:
>       TZ: Asia/Shanghai
>     ports:
>       - 8090:80
>     depends_on:
>       - go-ldap-admin-server
>     links:
>       - go-ldap-admin-server:go-ldap-admin-server
>     networks:
>       - go-ldap-admin
> ```
> 
> 我改了 openldap 容器的 env 變數 其他幾乎沒什麼變動

openldap 你改了这个
<img width="707" alt="image" src="https://github.com/eryajf/go-ldap-admin/assets/22713311/73a800bc-cc75-4b0e-9237-a30705d1a224">

**Comment by eryajf** [comment]
> demo 網站也無法用 admin/123456 登入唷..

感谢提醒，总会有人把demo改的不可用，现在已经恢复了。

**Comment by seed93** [comment]
demo现在还是不可用的状态，密码不对

>

**Comment by eryajf** [comment]
> demo现在还是不可用的状态，密码不对

感谢提醒，现已重置。

**Comment by Raven-L** [comment]
![image](https://camo.githubusercontent.com/7b7894bdac785109b0c6e7f0db202bfd6df3f316d2222f07e144886c303f4142/68747470733a2f2f692e696d6775722e636f6d2f374674724768562e706e67)
我也遇到了这个问题, 看了server的日志显示:
![image](https://github.com/eryajf/go-ldap-admin/assets/47520028/6838093a-eab0-449f-8880-167ae14fded7)

我的部署配置:
```
version: '3'

networks:
  go-ldap-admin:
    driver: bridge

services:
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/ali_eryajf/mysql-server:5.7
    container_name: go-ldap-admin-mysql # 指定容器名称，如果不设置此参数，则由系统自动生成
    hostname: go-ldap-admin-mysql
    restart: always # 设置容器自启模式
    ports:
      - '3307:3306'
    environment:
      TZ: Asia/Shanghai # 设置容器时区与宿主机保持一致
      MYSQL_ROOT_PASSWORD: 123456 # 设置root密码
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: go_ldap_admin
#    volumes:
##      # 数据挂载目录自行修改哦！
 #     - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
 #     - ./data/mysql:/var/lib/mysql/data # 映射数据库保存目录到宿主机，防止数据丢失
 #     - ./config/my.cnf:/etc/mysql/my.cnf # 映射数据库配置文件
    command: --default-authentication-plugin=mysql_native_password #解决外部无法访问
    networks:
      - go-ldap-admin

  openldap:
    image: registry.cn-hangzhou.aliyuncs.com/ali_eryajf/openldap:1.4.0
    container_name: go-ldap-admin-openldap
    hostname: go-ldap-admin-openldap
    restart: always
    environment:
      TZ: Asia/Shanghai
      LDAP_ORGANISATION: "eryajf.net"
      LDAP_DOMAIN: "eryajf.net"
      LDAP_ADMIN_PASSWORD: "123456"
    command: [ '--copy-service' ]
#    volumes:
#      - ./data/openldap/database:/var/lib/ldap
#      - ./data/openldap/config:/etc/ldap/slapd.d
#      - ./config/init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/init.ldif
    ports:
      - 388:389
    networks:
      - go-ldap-admin

  phpldapadmin:
    image: registry.cn-hangzhou.aliyuncs.com/ali_eryajf/phpldapadmin:0.9.0
    container_name: go-ldap-admin-phpldapadmin
    hostname: go-ldap-admin-phpldapadmin
    restart: always
    environment:
      TZ: Asia/Shanghai # 设置容器时区与宿主机保持一致
      PHPLDAPADMIN_HTTPS: "false" # 是否使用https
      PHPLDAPADMIN_LDAP_HOSTS: go-ldap-admin-openldap # 指定LDAP容器名称
    ports:
      - 8091:80
 #   volumes:
#      - ./data/phpadmin:/var/www/phpldapadmin
    depends_on:
      - openldap
    links:
      - openldap:go-ldap-admin-openldap # ldap容器的 service_name:container_name
    networks:
      - go-ldap-admin

  go-ldap-admin-server:
    image: eryajf/go-ldap-admin-server:2023-06-21_09-54
    container_name: go-ldap-admin-server
    hostname: go-ldap-admin-server
    restart: always
    environment:
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, openldap:389
    ports:
      - 8888:8888
    # volumes:  # 可按需打开此配置，将配置文件挂载到本地 可在服务运行之后，执行 docker cp go-ldap-admin-server:/app/config.yml ./config 然后再取消该行注释
    #   - ./config/config.yml:/app/config.yml
    depends_on:
      - mysql
      - openldap
    links:
      - mysql:go-ldap-admin-mysql # ldap容器的 service_name:container_name
      - openldap:go-ldap-admin-openldap # ldap容器的 service_name:container_name
    networks:
      - go-ldap-admin

  go-ldap-admin-ui:
    image: eryajf/go-ldap-admin-ui:2023-06-21_10-39
    container_name: go-ldap-admin-ui
    hostname: go-ldap-admin-ui
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 8090:80
    depends_on:
      - go-ldap-admin-server
    links:
      - go-ldap-admin-server:go-ldap-admin-server
    networks:
      - go-ldap-admin

```
如何解决这个问题?
